[package]
name = "benchmark"
version = "0.1.0"
edition.workspace = true
authors.workspace = true

[dependencies]
humantime = "2.1.0"
mcts = { path = "../mcts" }
game_rules = { path = "../game_rules" }
