[tasks.build-to-frontend]
category = "KinAI Automation"
dependencies = [
	"format",
	"build-release",
	"copy-to-frontend",
]

[tasks.copy-to-frontend]
category = "KinAI Automation"
script_runner = "@duckscript"
# platform overrides:
[tasks.copy-to-frontend.windows]
script = "exit 1"
[tasks.copy-to-frontend.mac]
script = "cp target/release/libkin_ai.dylib ../Frontend/KinAI.bundle"
[tasks.copy-to-frontend.linux]
script = "exit 1"
