[tasks.lint]
category = "Development"
dependencies = [
    "clippy-fix",
    "format",
]

[tasks.format]
toolchain = "nightly"

[tasks.clippy-fix]
category = "Development"
extend = "clippy"
args = ["clippy", "--fix", "--allow-dirty", "--allow-staged"]

[tasks.build-to-frontend]
category = "KinAI Automation"
dependencies = [
	"lint",
	"build-release",
	"copy-to-frontend",
]

[tasks.copy-to-frontend]
category = "KinAI Automation"
script_runner = "@duckscript"
# platform overrides:
[tasks.copy-to-frontend.windows]
script = "cp target/release/kin_ai.dll ../Frontend/KinAI.dll"
[tasks.copy-to-frontend.mac]
script = "cp target/release/libkin_ai.dylib ../Frontend/KinAI.bundle"
[tasks.copy-to-frontend.linux]
script = "exit 1"
